Import('env')

env.MLib('gred',
         srcs = Split ("""
                       gobj.cpp
                       action_manager.cpp
                       rubber.cpp
                       simple_viewer.cpp
                       mthread_viewer.cpp
                       dthread_viewer.cpp
                       """),
         deps = ['gtk'])

