Import('env')

e=env.Clone()
e.ParseConfig('pkg-config --cflags gtkmm-2.4')

e.Library('gred', \
    Split ("""
      gobj.cpp
      action_manager.cpp
      rubber.cpp
      simple_viewer.cpp
      mthread_viewer.cpp
      dthread_viewer.cpp
     """))

