Import ('env')

subdirs = Split ("""
  bigmap
  fig_mod
  gred_tests
  mp_bboxes
  ps
  srtm_pics
  srtm_riv
  tim
  image_a
  forest
  """)

SConscript(list(map(lambda s: s+"/SConscript", subdirs)))

