Import('env')

env.Library('fig', \
    Split ("""
        fig_io.cpp
        fig_mask.cpp
        fig_utils.cpp
        fig_data.cpp
     """))

e=env.Clone()
e.UseLibs('fig')
e.Program("catfig.cpp")
e.Install(env.bindir, ['catfig'])

