Import('env')

env.MLib('fig',
         srcs = Split ("""
                  fig_io.cpp
                  fig_mask.cpp
                  fig_utils.cpp
                  fig_data.cpp
                  """),
         deps = ['utils',
                 '2d'])

env.MProg('catfig',
          srcs = ['catfig.cpp'],
          deps = ['fig'])

env.Install(env.bindir, ['catfig'])

