#!/bin/bash

CONFDIR=$HOME/.poehali

POECODE=`which poecode`
GOCR=`which gocr`

if [ ! -d $CONFDIR ]; then mkdir $CONFDIR || exit; fi
if [ ! -f $CONFDIR/mapmapstor ]; then echo "01" > $CONFDIR/mapmapstor; fi

rm -f $CONFDIR/cookie $CONFDIR/gifcode $CONFDIR/code.png # $CONFDIR/gifmapstor

mapmapstor=`cat $CONFDIR/mapmapstor`

# Для беззвучного убийства display
set +m

# Пишу cookies и #gifmapstor# для карт
wget http://mapstor.com/mapstorfile.php?file=050k--n37-027-2.gif -O/dev/null --save-cookies=$CONFDIR/cookies --keep-session-cookies >/dev/null 2>&1 #| grep 'm.\+\.mapstor\.com' | sed -n '1 s/.*m\(.\+\)\.mapstor\.com.*/\1/p' > $CONFDIR/gifmapstor
# Пишу cookies для привязок
wget http://m$mapmapstor.mapstor.com/p_getfileref.php?m=n37%2F050k%2F050k--n37-027-2.map -O/dev/null --load-cookies=$CONFDIR/cookies --save-cookies=$CONFDIR/cookies --keep-session-cookies > /dev/null 2>&1

sid=`awk '/nbmpgf/ {print $7}' $CONFDIR/cookies`
giftmt=`date +%s`

echo $giftmt > $CONFDIR/giftmt

# Скачиваю картинку с кодом для карт и спрашиваю, что нарисовано
gifmapstor=`cat $CONFDIR/gifmapstor`
wget --load-cookies=$CONFDIR/cookies -O $CONFDIR/code.png "http://m$gifmapstor.mapstor.com/p_getfile.php?mode=showpic&sid=$sid&tmt=$giftmt" >/dev/null 2>&1 

if [ -n "$POECODE" -a -x "$POECODE" -a -n "$GOCR" -a -x "$GOCR" ]
then
   $POECODE $CONFDIR/code.png $CONFDIR/code-clean.png > /dev/null
   $GOCR -C 0123456789 $CONFDIR/code-clean.png > $CONFDIR/gifcode
   printf "Код для карт: "
   cat $CONFDIR/gifcode
   rm $CONFDIR/code.png $CONFDIR/code-clean.png
else
   display $CONFDIR/code.png &
   printf "Введите код для карт: "
   read code
   echo $code > $CONFDIR/gifcode
   kill %- 2>/dev/null
   wait %- 2>/dev/null
   rm $CONFDIR/code.png
fi

maptmt=`date +%s`

echo $maptmt > $CONFDIR/maptmt

# Скачиваю картинку с кодом для привязок и спрашиваю, что нарисовано
wget --load-cookies=$CONFDIR/cookies -O $CONFDIR/code.png "http://m$mapmapstor.mapstor.com/p_getfileref.php?mode=showpic&sid=$sid&tmt=$maptmt" >/dev/null 2>&1 

if [ -n "$POECODE" -a -x "$POECODE" -a -n "$GOCR" -a -x "$GOCR" ]
then
   $POECODE $CONFDIR/code.png $CONFDIR/code-clean.png > /dev/null
   $GOCR -C 0123456789 $CONFDIR/code-clean.png > $CONFDIR/mapcode
   printf "Код для привязок: "
   cat $CONFDIR/mapcode
   rm $CONFDIR/code.png $CONFDIR/code-clean.png
else
   display $CONFDIR/code.png &
   printf "Введите код для привязок: "
   read code
   echo $code > $CONFDIR/mapcode
   kill %- 2>/dev/null
   wait %- 2>/dev/null
   rm $CONFDIR/code.png
fi

# vim: tw=0
