Import('env')
e=env.Clone()
e.UseLibs('utils')

e.Program("srtm_riv.cpp")

e.Program("one_river", Split("one_river.cpp point.cpp map.cpp"))
e.Program("arrows",    Split("arrows.cpp point.cpp map.cpp"))
e.Program("rivers",    Split("rivers.cpp point.cpp map.cpp"))
e.Program("rtext",     Split("rtext.cpp font.cpp point.cpp map.cpp"))



