Import('env')
e=env.Clone()
e.UseLibs('srtm options')

e.Program("srtm_riv.cpp")

e.Program("one_river", Split("one_river.cpp map.cpp"))
e.Program("arrows",    Split("arrows.cpp map.cpp"))
e.Program("rivers",    Split("rivers.cpp map.cpp"))
e.Program("rtext",     Split("rtext.cpp font.cpp map.cpp"))
e.Program("srtm2pnm.cpp")



