Import ('env')
le = env.Clone()

le.MProg('generic_accessor_unittest',
         srcs = ['generic_accessor_unittest.cpp'],
         deps = ['utils'])

le.MProg('cache_test',
         srcs = ['cache_test.cpp'],
         deps = ['utils'])

#le.MProg('options_test',
#         srcs = ['options_test.cpp'],
#         deps = ['utils'])

