Import ('env')

subdirs = Split ("""
    2d_rectcrop
    2d_angles
    2d_cache
    margin_classifier
    types_io
    geo_nom
    options
  """)

SConscript (map (lambda(s): s+"/SConscript", subdirs))

