Import ('env')

subdirs = Split ("""
    2d_rectcrop
    2d_point
    2d_rectcrop_ml
    2d_nearest_pt
    2d_angles
    2d_rainbow
    generic_accessor
    margin_classifier
    types_io
    geo_nom
    options
    srtm
  """)

SConscript (list(map (lambda s: s+"/SConscript", subdirs)))

