Import ('env')
env.Library('vmap', \
  Split ("""
     zn.cpp
     zn_lists.cpp
     vmap.cpp
     vmap_file.cpp
     vmap_fig.cpp
     vmap_mp.cpp
     vmap_ocad.cpp
     vmap_vmap.cpp
     vmap_cnv.cpp
     vmap_filt.cpp
     vmap_labels.cpp
     vmap_ref.cpp
     vmap_legend.cpp
   """))
