#!/bin/sh -efu

for z in $(seq 1 17); do
  f="google$z"
  ts=256
  tc="$((2**$z))" # max tile number + 1
  fmt="%0${#tc}dx%0${#tc}d.jpg"

  wg=20037508.342789244
  wr=$(($ts*$tc))

cat > ${f%.txt}.xml << EOF
<maps>
  <map file="$f" comm="google $z" map_proj="google"
       border="0,0,$wr,0,$wr,$wr,0,$wr"
       tile_size="$ts" tile_fmt="$fmt">
    <pt proj="google" x="-$wg" y="$wg"  xr=0 yr=0/>
    <pt proj="google" x="$wg"  y="$wg"  xr=$wr yr=0/>
    <pt proj="google" x="$wg"  y="-$wg" xr=$wr yr=$wr/>
    <pt proj="google" x="-$wg" y="-$wg" xr=0 yr=$wr/>
  </map>
</maps>
EOF

mkdir -p -- "$f"

#https://khms1.google.com/kh/v=113&src=app&x=3&y=3&z=3&s=Gali

cat > "$f/download" << EOF
#!/bin/sh -efu

ver=113
z=$z
nn="\$(head -c1 /dev/urandom | od -to1 -An | tail -c2)" # 0..7
nn="\$((\$nn/2))" # 0..3 random
gal="\$(echo "Galileo" | head -c "\$(( (\$1*3+\$2)%8))")" #"
url="http://khm\${nn}.google.com/kh/v=\${ver}&x=\${1}&y=\${2}&z=\${z}&s=\${gal}";

f=\$(printf "$fmt" "\$1" "\$2")
echo "Downloading \$f"
wget "\$url" -O "\$f" || rm -f -- "$f"
EOF
chmod 755 "$f/download"

done
