Import ('env')
le = env.Copy()
sources = Split ("""
		image_jpeg.cpp
		image_tiff.cpp
		image_png.cpp
		image_i.cpp
		image_r.cpp
		image_google.cpp
		""")

le.Library('loaders', sources, LIBS=Split('tiff jpeg png'))
