Import('env')

env.MLib('mp',
         srcs = Split("""
                      mp_io.cpp
                      mp_mask.cpp
                      mp_data.cpp
                      """))

env.MProg('catmp',
          srcs = ['catmp.cpp'],
          deps = Split("""mp utils 2d"""))

env.Install(env.bindir, ['catmp'])

