Import('env')

env.Library('mp', \
    Split ("""
        mp_io.cpp
        mp_mask.cpp
        mp_data.cpp
     """))

e=env.Clone()
e.ParseConfig('pkg-config --cflags --libs mp')
e.Program("catmp.cpp")
e.Install(env.bindir, ['catmp'])

