Import('env')

env.MLib('mp',
         srcs = Split("""
                      mp_io.cpp
                      mp_mask.cpp
                      mp_data.cpp
                      """),
         deps = Split("""
                  utils
                  2d
                  options
                  """))

env.MProg('catmp',
          srcs = ['catmp.cpp'],
          deps = ['mp'])

env.Install(env.bindir, ['catmp'])

