Import ('env')
env.Library('geo', \
    Split ("""
	geo_convs.cpp
	geo_data.cpp
	geo_types.cpp
   geo_refs.cpp
     """))

convs_libs=Split("geo loaders jeeps utils 2d png jpeg tiff")
env.Program("convs_pt2pt.cpp",  LIBS=[convs_libs])

env.Alias('install', '/usr/bin/')
env.Install('/usr/bin/', 'convs_pt2pt')
