#!/usr/bin/perl -w
use strict;
use Encode;

my $l1 = join(" ", <STDIN>);

while ($l1 =~ m|<Placemark>(.*?)</Placemark>|sg){
    my $per = $1;

    $per =~ m|<name>(.*?)</name>|s; my $name = $1;
    $per =~ m|<th>Другие\s+названия</th><td>(.*?)</td>|s;     my $altname = ($1 eq '')? '':" ($1)";
    $per =~ m|<th>Категория\s+сложности</th><td>(.*?)</td>|s; my $ks = $1;
    $per =~ m|<th>Высота</th><td>(.*?)</td>|s;                my $alt = $1;
    $per =~ m|http://www.westra.ru/passes/Passes/(\d+)|s;     my $westra_n = $1;
    $per =~ m|<longitude>(.*?)</longitude>|s;                 my $lon = $1;
    $per =~ m|<latitude>(.*?)</latitude>|s;                   my $lat = $1;

printf "%5d %11.7f %12.7f %4d %-6s %s\n", $westra_n, $lat, $lon, $alt, $ks, $name.$altname;

}
