#!/usr/bin/perl -w
use strict;
use Encode;

my $l = decode('utf-8', join(" ", <STDIN>));
my $l1 = encode('koi8-r', $l);

print qq*[IMG ID]\r
ID=0\r
Name=\r
Elevation=M\r
Preprocess=F\r
CodePage=KOI8-R\r
LblCoding=9\r
TreSize=511\r
TreMargin=0.000000\r
RgnLimit=127\r
Transparent=Y\r
POIIndex=N\r
Levels=4\r
Level0=22\r
Level1=21\r
Level2=19\r
Level3=17\r
Zoom0=0\r
Zoom1=1\r
Zoom2=2\r
Zoom3=3\r
[END-IMG ID]\r
*;

while ($l1 =~ m|<Placemark>(.*?)</Placemark>|sg){
    my $per = $1;

    $per =~ m|<name>(.*?)</name>|s; my $name = $1;
    $per =~ m|<th>Другие\s+названия</th><td>(.*?)</td>|s;     my $altname = ($1 eq '')? '':" ($1)";
    $per =~ m|<th>Категория\s+сложности</th><td>(.*?)</td>|s; my $ks = $1;
    $per =~ m|<th>Высота</th><td>(.*?)</td>|s;                my $alt = $1;
    $per =~ m|http://www.westra.ru/passes/Passes/(\d+)>|s;    my $westra_n = $1;
    $per =~ m|<longitude>(.*?)</longitude>|s;                 my $lon = $1;
    $per =~ m|<latitude>(.*?)</latitude>|s;                   my $lat = $1;

my $type = "0x6406";
$type = "0x6620" if ($ks =~ /н\/к/) || ($ks =~ /н.к/) || ($ks =~ /Н.К/) || ($ks =~ /Н\/К/);
$type = "0x6621" if ($ks =~ /1А/) || ($ks =~ /1а/);
$type = "0x6622" if ($ks =~ /1Б/) || ($ks =~ /1б/);
$type = "0x6623" if ($ks =~ /2А/) || ($ks =~ /2а/);
$type = "0x6624" if ($ks =~ /2Б/) || ($ks =~ /2б/);
$type = "0x6625" if ($ks =~ /3А/) || ($ks =~ /3а/);
$type = "0x6626" if ($ks =~ /3Б/) || ($ks =~ /3б/);
$type = "0x1100" if ($name =~ /^в./);

my $label;
if ($type ne "0x1100") {$label = $name;}
else {$label = "$alt $name"; next; }# нам пока вершины не нужны...

$label =~ s/&quot;/\"/g;

my $out = qq*
; $type 0000-00-00 00:00:00 $westra_n\@westra_passes
[POI]\r
Type=$type\r
Label=$label\r
EndLevel=1\r
Data0=($lat,$lon)\r
[END]\r
*;

my $o1 = decode('koi8-r', $out);
my $o2 = encode('cp1251', $o1);
print $out;

}