#!/bin/sh -eu

PROG="${0##*/}"

usage(){
  echo "$PROG -- update tile map www dir"
  echo "usage: $PROG <name>"
  exit 1
}

[ "$#" = 1 ] || usage

name="$1"

if [ ! -d "$name" ]; then
  echo "error: can't find tmap: $name"
  exit 1
fi

png_scale=0.4

style="$(head -n1 "$name/.style")"
[ -n "$style" ] || style="default"

wwwdir="$name.www"
mkdir -p -- "$wwwdir"

for vmap in $name/*.vmap; do
  base="$(basename "$vmap" .vmap)"
  png="$wwwdir/$base.png"
  map="$wwwdir/$base.map"
  if [ "$png" -ot "$vmap" ]; then
    echo "Rendering: $base"
    vmap_render -m "$map" -ND "$vmap" "$png"
    map_rescale -s "$style" -r "$png_scale" "$map"
  fi
done

