#!/bin/sh -eu

PROG="${0##*/}"

usage(){
  echo "$PROG -- update www representations of tmap git-repositary"
  echo "usage: $PROG"
  exit 1
}

[ "$#" = 0 ] || usage

# name of tmap dir
tmap="tmap"
png_scale=0.3


if [ ! -d "$tmap" ]; then
  echo "error: can't find tmap dir: $name"
  exit 1
fi
style="$(head -n1 "$tmap/.style")"
[ -n "$style" ] || style="default"


cat > history.htm <<-EOF
	<html>
	<body>
	<ul>
	EOF

mkdir -p -- "tiles"
rm -f -- tiles/*.txt

git log --pretty=format:'%H%x09%aN <%aE>%x09%at%x09%s' |
while IFS='	' read sha auth t subj; do
  comm_dir="commits/$sha"

  mkdir -p -- "$comm_dir"
  printf "%s\t%s\t%s\n" "$auth" "$t" "$subj" > "$comm_dir/info"

  d="$(date -d "@$t" "+%Y/%m/%d %H:%M:%S")"
  cat >> history.htm <<-EOF
	<li><b>$d: $auth: $subj</b><br>
	EOF

  git show --pretty=format:'' --stat $sha |
  while IFS='|' read f g; do
    [ -n "$g" ] || continue
    f="${f##*/}"
    f="${f%.*}"
    echo "<a href=\"tiles/$f.htm\">${f#t.}</a> " >> history.htm
    if [ ! -f "$comm_dir/$f.png" ]; then 
      echo "Rendering PNG: ${f#t.}"
      tmp="$(mktemp).vmap"
      git cat-file blob "$sha:$tmap/$f.vmap" > $tmp
      vmap_render -m "$comm_dir/$f.map" "$tmp" "$comm_dir/$f.png"
      map_rescale -s "$style" -r "$png_scale" "$comm_dir/$f.map"
      rm -f -- "$tmp"
    fi
    printf "%s\t%s\n" "$sha" "$subj"  >> "tiles/$f.txt"
  done
done

cat >> history.htm <<-EOF
	</ul>
	</body>
	</html>
	EOF

for txt in tiles/*.txt; do
  htm="${txt%.txt}.htm"
  base="$(basename "$txt" .txt)"
  pref="${base%%.*}"
  nums="${base#$pref.}"
  y="${nums#*.}"
  x="${nums%.*}"

  l="${pref}.$(($x-1)).${y}"
  u="${pref}.${x}.$(($y+1))"
  d="${pref}.${x}.$(($y-1))"
  r="${pref}.$(($x+1)).${y}"
  nav=
  [ -f "$tmap/$l.vmap" ] && nav="$nav <a href=\"$l.htm\">[left]</a>"  || nav="$nav [left]"
  [ -f "$tmap/$u.vmap" ] && nav="$nav <a href=\"$u.htm\">[up]</a>"    || nav="$nav [up]"
  [ -f "$tmap/$d.vmap" ] && nav="$nav <a href=\"$d.htm\">[down]</a>"  || nav="$nav [down]"
  [ -f "$tmap/$r.vmap" ] && nav="$nav <a href=\"$r.htm\">[right]</a>" || nav="$nav [right]"

  cat > "$htm" <<-EOF
	<html>
	<body>
	<center>
	<h4>$nav</h4>
	EOF

  while IFS='	' read sha subj; do
    cat >> "$htm" <<-EOF
	<img src="../commits/$sha/$base.png"><br>
	$subj<br>
	<a href="../commits/$sha/$base.map">[MAP]</a><br>
	EOF
  done < "$txt"

  cat >> "$htm" <<-EOF
	</center>
	</body>
	</html>
	EOF
done
