#!/bin/sh -efu

PROG="${0##*/}"

rscale=50000
style=mmb
tsize=0.1

usage(){
  echo "$PROG -- tile map init"
  echo "usage: $PROG [<options>] <name>"
  echo "options:"
  echo " -r <rscale> -- set rscale (default $rscale)"
  echo " -s <style>  -- set style (default $style)"
  echo " -t <tsize>  -- set tsize (default $tsize)"
  exit 1
}

opts="hr:s:t:"
TEMP=`getopt -n "$PROG" -o $opts -- "$@"` || usage
eval set -- "$TEMP"

while :; do
  case "$1" in
    -h) usage ;;
    -r) rscale="$2"; shift ;;
    -t) tsize="$2"; shift ;;
    -s) style="$2"; shift ;;
    --) shift; break ;;
  esac
  shift
done

[ "$#" = 1 ] || usage

name="$1"

if [ -d "$name" ]; then 
  echo "error: dir exists: $name"
  exit 1
fi

mkdir -- "$name"
echo "$rscale" > "$name/.rscale"
echo "$tsize" > "$name/.tsize"
echo "$style" > "$name/.style"

