Import ('env')

mapsoft_libs = Split ("zn geo_io geo loaders jeeps fig mp utils options 2d")
other_libs   = Split ("curl usb tiff jpeg png gd yaml proj")

env1 = env.Clone()
env1.Prepend(LIBS=[mapsoft_libs,other_libs])

env1.Program('fig2ps.cpp')



