Import ('env')
e=env.Clone()

e.MLib('utils',
       srcs = Split("""
                    log.cpp
                    iconv_utils.cpp
                    spirit_utils.cpp
                    pnm_shifter.cpp
                    cairo_wrapper.cpp
                    """),
       deps = ['cairo'])

SConscript ("tests/SConscript")
