Import ('env')
e=env.Clone()
e.UseLibs('cairomm-1.0 pixman-1 freetype2')

e.Library('utils', \
  Split("""
    log.cpp
    iconv_utils.cpp spirit_utils.cpp
    pnm_shifter.cpp
    cairo_wrapper.cpp
  """))

