Import ('env')
le = env.Clone()
le.Library('geo_io', \
    Split ("""
        io.cpp
	io_gu.cpp
    	io_oe.cpp
	io_gps.cpp
	io_xml.cpp
	io_kml.cpp
	geo_enums.cpp
	filters.cpp
	geo_convs.cpp
	o_fig.cpp
	o_htm.cpp
	geofig.cpp
	geo_data.cpp
     """))
