
mapsoft_libs=Split("geo_io geo loaders fig utils options 2d jeeps")
other_libs=Split("proj png jpeg tiff")

Import('env')
e=env.Clone()
e.Prepend(LIBS=[mapsoft_libs, other_libs])

e.Program("fig_crop.cpp")
e.Program("fig_ref_mod.cpp")
e.Program("fig_sort.cpp")


