#!/bin/sh -efu

prog=core/getopt/getopt.test

function do_test(){
  args=$1
  exp=$2
  res="$($prog $args 2>&1)" ||:
  if [ "$res" != "$exp" ]; then
    echo "ERROR:"
    echo "  args: \"$args\""
    echo "  exp:  \"$exp\""
    echo "  res:  \"$res\""
    return 1
  fi
  return 0
}

 

do_test '-v' ''
do_test '-v -I' 'error: missing argument: -I'
do_test '-v -I 1' ''
do_test '-v -I 1 -J file1'\
        'reading: file1 options: {"inp1": "1", "inp2": "1", "verbose": "1"}'
do_test '-v -O -I 1 -J file1'\
        'error: unknown option: -O'
do_test '-v -I 1 -J file1 -o -J'\
        'error: wrong position of --out option'

do_test '-v -I 1 -J file1 -o file2 -J'\
 'reading: file1 options: {"inp1": "1", "inp2": "1", "verbose": "1"}
error: unknown option: -J'

do_test '-v -I 1 -J file1 -C 1 -o file2 -C'\
 'reading: file1 options: {"cmn1": "1", "inp1": "1", "inp2": "1", "verbose": "1"}
error: missing argument: -C'

do_test '-v -I 1 -J file1 -C 1 -o file2 -C 1 -D'\
 'reading: file1 options: {"cmn1": "1", "inp1": "1", "inp2": "1", "verbose": "1"}
writing: file2 options: {"cmn1": "1", "cmn2": "1"}'

do_test '-v -I 1 file1 -C 10 -J file2 -C 20 -o file3 -C 1 -D' \
'reading: file1 options: {"cmn1": "10", "inp1": "1", "inp2": "1", "verbose": "1"}
reading: file2 options: {"cmn1": "20", "inp1": "1", "verbose": "1"}
writing: file3 options: {"cmn1": "1", "cmn2": "1"}'

exit 0