#!/bin/sh -efu

# directory with source vmap files
vmap_dir=./map_podm
nom_rscale=50000 # just to get correct map names
fig_rscale=89415 # scale in google proj units / m = 50000/cos(56d)

# scale and size of "big" google tile
sc=9
tile_size_px = 4096 # 256 * 8

# tiles to create
x1=310
x2=310
y1=160
y2=161

k=20037508.3 # mapsoft google proj units (equator meters) per scale=1 tile

# size of map, cm
map_size_cm="$(dc -e "10k $k 2 $sc 1 - ^ / $fig_rscale / 100 * p")"

# dpi to get tile_size_px
tile_dpi = "$(dc -e "10k $tile_size_px $map_size_cm 2.54 / / p")"

######################################################################

update_tile(){
  local x=$1;
  local y=$2;

  echo "tile: $x $y"
  local x1 x2 y1 y2 dx dy

  x1="$(dc -e "10k $x 2 $sc 1 - ^ / 1 - $k * p")"
  x2="$(dc -e "10k $x 1 +  2 $sc 1 - ^ / 1 - $k * p")"

  y1="$(dc -e "10k 1 $y 1 + 2 $sc 1 - ^ / - $k * p")"
  y2="$(dc -e "10k 1 $y 2 $sc 1 - ^ / - $k * p")"

  dx="$(dc -e "10k $x2 $x1 - p")"
  dy="$(dc -e "10k $y2 $y1 - p")"

  geom="${dx}x${dy}+$x1+$y1"

  # geom in Pulkovo LonLat:
  geom_pll="$(echo "bb_frw $geom 1" |
    convs_pt2pt "wgs84" "google" "" "pulkovo" "lonlat" "")"

#  echo "geom: $geom"
#  echo "geom_ll: $geom_pll"

  fig="t$x-$y.fig"

  nom_list="$(convs_nom -r "$geom_pll" "$nom_rscale")"
  src=
  need_update=
  for i in $nom_list; do
    f=$vmap_dir/$i.vmap
    [ -f "$f" ] || continue
    src="$src $f";
    [ -f "$fig" -a "$f" -ot "$fig" ] || need_update=1
  done
  [ -n "$need_update" ] || return 0

#  echo "src maps: $src"

  # create fig files if needed
  if [ ! -f "$fig" ]; then
    mapsoft_convert --geom="$geom" --proj=google --datum=wgs84\
      --rscale="$fig_rscale" --dpi=1 --out="$fig".jpg --fig="$fig"
    rm -f -- "$fig".jpg
    sed -i -e '/# MAP/,$d' "$fig"
    my_src="$src"
  else
    # use old labels if fig file exists:
    my_src="--skip_labels $src $fig --read_labels --skip_all"
  fi

  # copy vmaps
  # join_objects is very slow - i turn it off for tests
  vmap_copy -v $my_src --out $fig\
    --range_datum=wgs84 --range_proj=google --range="$geom"\
    --set_brd_from_range --range_action=crop_spl # --join_objects 1e-4

}

######################################################################

for x in $(seq $x1 $x2); do
  for y in $(seq $y1 $y2); do
    update_tile "$x" "$y"
  done
done
