#!/bin/sh -efu

std="
string vector map list set queue
iostream sstream fstream iomanip ios
cstdlib cstdio  cassert cmath cstring cerrno ctime
math.h stdarg.h stddef.h stdio.h stdlib.h string.h time.h limits.h unistd.h
sys\/types.h sys\/stat.h sys\/time.h getopt.h assert.h errno.h fcntl.h
"
showboost=

std=$(printf "%s" "$std" | tr '\n' ' ' | sed 's/[[:space:]]/\\|/g')
[ -z "$showboost" ] &&
  showboost="/<\(boost\/[^\.\/]*\).*>/d" ||
  showboost="s/<\(boost\/[^\.\/]*\).*>/  \1/"

dirs="$(find . -maxdepth 1 -type d)"
for d in $dirs; do
  [ "$d" != "." ] || continue
  files="$(find "$d" -name "*.cpp" -or -name "*.h")"

  echo "== $d =="
  sed -n -e "
    /^#include/{
      s/^#include[[:space:]]\+\([\"<][^\"<]\+[\">]\).*/\1/
      /^\"[^/]\+\"/d      # skip local
      /^<\($std\)>/d    # skip std

      s/\"\([^/]\+\)\/[^/]\+\"/\1/

      $showboost

      s/<proj_api.h>/  libproj/
      s/<yaml.h>/  libyaml/
      s/<iconv.h>/  libiconv/
      s/<curl\/curl.h>/  libcurl/
      s/<jpeglib.h>/  libjpeg/
      s/<png.h>/  libpng/
      s/<tiffio.h>/  libtiff/

      s/<cairomm.*>/  cairomm/
      s/<gtkmm.h>/  gtkmm/
      s/<gdkmm\/.*>/  gdkmm/
      s/<gdk\/.*>/  gdm/
      p
    }
  " $files | LC_ALL=C sort -u
  echo
done
