Import('env')

env.MProg('rectcrop',
          srcs = ['rectcrop.cpp'],
          deps = ['2d',
                  'fig'])

env.MProg('crop_ml',
          srcs = ['crop_ml.cpp'],
          deps = ['2d',
                  'fig'])
