#!/bin/sh -efu

srtm_pic="./srtm_pic"

if [ "$#" -lt 1 ]; then
  cat << EOF
$0 -- wrapper for $srtm_pic program.

usage: $0 <name1> <name2> ...

Reads srtm_pic_data.txt and makes png image and map-file for each name.

format of srtm_pic_data.txt file:
  each line contains the following info:
  <name> <style: hr|podm> <lon0> <X1> <X2> <Y1> <Y2>
  lines started with # end empty lines are ignored

srtm_pic_data.txt example:
  giss_test hr 69 436000 440000 4310000 4316000
EOF
fi

for n in "$@"; do
  found=
  while read name style geom; do
    [ -n "${name%%*#}" ] || continue

    [ "$n" = "$name" ] || continue

    echo "<<$name>>"
    [ "$style" = "podm" ] && steps="10 10" || steps="50 50"
    ./srtm_pic 1e-5 200 $geom $steps $style > "$name.pnm"
    pnmquant 255 < "$name.pnm" | pnmtopng > "$name.png"
    sed -e "3s/.*/$name.png/" "srtm_pic_out.map" > "$name.map"
    rm -f -- "srtm_pic_out.map" "$name.pnm"
    found=1
  done < srtm_pic_data.txt
  [ -n "$found" ] || echo "Unknown name <<$n>>"
done
