#!/bin/sh -efu

srtm_pic="./srtm_pic"

if [ "$#" -lt 1 ]; then
  cat << EOF
$0 -- wrapper for $srtm_pic program.

usage: $0 <name1> <name2> ...

Reads srtm_pic_data.txt and makes png image and map-file for each name.

format of srtm_pic_data.txt file:
  each line contains the following info:
  <name> <style: hr|podm> <lon0> <X1> <X2> <Y1> <Y2>
  lines started with # end empty lines are ignored

srtm_pic_data.txt example:
  giss_test hr 69 436000 440000 4310000 4316000
EOF
fi

for n in "$@"; do
  found=
  while read name style geom; do
    [ -n "${name%%*#}" ] || continue
    [ "$n" = "$name" ] || continue
    echo "<<$name>>"

    if [ "$style" = "podm" ]; then
       step=10
       smin=5
       smax=30
    else
       step=50
       smin=30
       smax=55
    fi

    ../../programs/mapsoft_convert\
       --srtm_mode slopes --srtm_smin $smin --srtm_smax $smax\
       --srtm_cnt_step $step\
       --geom $geom --rscale 100000 --dpi 200\
       -m "$name.map" -o "$name.png"

#    pngtopnm "$name.png" | pnmquant 255 | pnmtopng > "$name.png"
    found=1
  done < srtm_pic_data.txt
  [ -n "$found" ] || echo "Unknown name <<$n>>"
done
