Import ('env')

env.Library('loaders', \
    Split("""
	image_jpeg.cpp
        image_tiff.cpp
        image_png.cpp
        image_r.cpp
    """))

e=env.Clone()
e.UseLibs('loaders')
e.Program("img_convert.cpp")
 