#!/bin/bash

VMAP="/home/sla/MS3/libzn-utils/mapsoft_vmap"

MAP="all.fig"
CONF="./conf"

if [ -z "$MAP" ]; then 
  echo "usage: $0"
  exit 1
fi

maps="$($VMAP show_maps $CONF $MAP| cut -f1)"

for m in $maps; do
  echo "$m"
  $VMAP remove "$CONF"        "$m".fig all
  $VMAP copy   "$CONF" "$MAP" "$m".fig map "$m"
  $VMAP labels "$CONF"        "$m".fig
  $VMAP pics   "$CONF"        "$m".fig
done
