#!/bin/bash

VMAP="/home/sla/MS3/libzn-utils/mapsoft_vmap"

MAPS="$@"

ALL_NAME="all.fig"
CONF="./conf"

if [ -z "$MAPS" -o -z "$CONF" -o -z "$ALL_NAME" ]; then 
  echo "usage: $0 <MAPS.fig>"
  exit 1
fi

cp "$1" "$ALL_NAME"

$VMAP remove_grids  "$CONF" "$ALL_NAME"
$VMAP remove_labels "$CONF" "$ALL_NAME"
$VMAP remove        "$CONF" "$ALL_NAME" all
for i in $@; do
  echo $i
  $VMAP copy        "$CONF" "$i" "$ALL_NAME" all
  $VMAP copy_labels "$CONF" "$i" "$ALL_NAME" all
done
