#!/bin/bash

. ../settings.sh

MAPS="$@"

ALL_NAME="all.fig"

if [ -z "$MAPS" -o -z "$CONF" -o -z "$ALL_NAME" ]; then 
  echo "usage: $0 <MAPS.fig>"
  exit 1
fi

cp "$1" "$ALL_NAME"

mapsoft_vmap remove_grids  "$CONF" "$ALL_NAME"
mapsoft_vmap remove_labels "$CONF" "$ALL_NAME"
mapsoft_vmap remove        "$CONF" "$ALL_NAME" all
for i in $@; do
  echo $i
  mapsoft_vmap copy        "$CONF" "$i" "$ALL_NAME" all
  mapsoft_vmap copy_labels "$CONF" "$i" "$ALL_NAME" all
done
