Import('env')

env.Library('mp', \
    Split ("""
        mp_io.cpp
        mp_mask.cpp
        mp_data.cpp
     """))

libs=Split("mp utils 2d")
env.Program("catmp.cpp",  LIBS=[libs])

env.Install(env.bindir, ['catmp'])

