env = Environment ()

mapsoft_libs=Split("geo_io geo loaders fig utils options 2d jeeps")
other_libs=Split("proj png jpeg tiff")

env.Append (CCFLAGS=['-O2'])
env.Append (CPPPATH = ["../../core"])
env.Append (LIBPATH = map(lambda(s): "../../core/"+s, mapsoft_libs) )
env.Append (LIBS = [mapsoft_libs, other_libs] )

env.Program("fig_crop.cpp")
env.Program("fig_ref_mod.cpp")
env.Program("fig_sort.cpp")


