#!/bin/sh -eu

mkdir -p results expected
for i in test_data/*.fig; do
  base="${i##*/}"
  ./nearest_pt "test_data/$base" "results/$base"
  if [ -s "expected/$base" ]; then
    diff -- "results/$base" "expected/$base"
  else
    cp -f -- "results/$base" "expected/$base"
  fi
done