Import ('env')

e=env.Clone()
e.UseLibs('gred geo_io mp')

e.Library("viewer", Split ("""
	action_manager.cpp
	workplane.cpp widgets.cpp dataview.cpp mapview.cpp
        """))
e.Prepend(LIBS=["viewer"])
e.Program("mapsoft_mapview.cpp")

#le.Program('mapsoft_googleview', "mapsoft_googleview.cpp")
#le.Program('mapsoft_ksview', "mapsoft_ksview.cpp")

env.Install(env.bindir, Split("""
  mapsoft_mapview
"""))
