Import('env')

env.Library('vmap', \
    Split ("""
        vmap_id.cpp
        vmap_io.cpp
        vmap_io_dir.cpp
        vmap_io_mp.cpp
        legend.cpp
    """))

libs=Split("vmap fig mp zn utils 2d yaml")
env.Program("test_mp2dir.cpp",  LIBS=[libs])
env.Program("test_dir2mp.cpp",  LIBS=[libs])
