Import('env')
e = env.Clone()

e.ParseConfig('pkg-config --cflags --libs gred gtkmm-2.4')

files=Split('gobj_test_tile.cpp gobj_test_grid.cpp gobj_solid_fill.cpp')

map (lambda(f): e.Program([f+'.cpp'] + files),\
  Split("""
    simple1
    simple2
    mthread1
    mthread2
    dthread1
    dthread2
    dthread_line
    simple_rubb1
    simple_rubb2
    mthread_rubb1
    dthread_rubb1
    action1
    action2
    action3
    all_viewers
    two_rubbers
    """))



