Import('env')

files=Split('gobj_test_tile.cpp gobj_test_grid.cpp gobj_solid_fill.cpp')

progs = Split("""
    simple1
    simple2
    dthread1
    dthread2
    dthread_line
    simple_rubb1
    simple_rubb2
    dthread_rubb1
    action1
    action2
    action3
    all_viewers
    two_rubbers
    """)

for p in progs:
  env.Program([p+'.cpp'] + files)




