Import ('env')

env.Install(env.datadir, Split("""
  pics/ mmb.cnf hr.cnf default.cnf
"""))

env.Install(env.datadir, Split("pics"))


e = env.Clone()
e.UseLibs('vmap')

e.Program('zn_figlib.cpp')
e.Program('zn_legend.cpp')
e.Program('zn_text.cpp')
