env = Environment ()

mapsoft_libs = Split("geo_io geo loaders fig mp utils options 2d jeeps")
other_libs   = Split ("usb tiff jpeg png curl proj")

env.Append (CCFLAGS=['-O2'])
env.Append (CPPPATH = ["../../core"])
env.Append (LIBPATH = map(lambda(s): "../../core/"+s, mapsoft_libs) )
env.Append (LIBS = [mapsoft_libs, other_libs] )
env.ParseConfig('pkg-config --cflags --libs cairomm-1.0,freetype2')

map (lambda(f): env.Program(f+'.cpp'),\
  Split("""
    mapsoft_measure
    mapsoft_mark
    mapsoft_trackprofile
    mapsoft_srtmprofile
    """))
