
mapsoft_libs = Split("geo_io geo loaders fig mp utils options 2d jeeps")
other_libs   = Split ("usb tiff jpeg png curl proj")

Import('env_cairo')
e=env_cairo.Clone()
e.Prepend(LIBS=[mapsoft_libs, other_libs])

map (lambda(f): e.Program(f+'.cpp'),\
  Split("""
    mapsoft_measure
    mapsoft_mark
    mapsoft_trackprofile
    mapsoft_srtmprofile
    """))
