Import('env')
e=env.Clone()

e.ParseConfig('pkg-config --cflags --libs geo_io')

map (lambda(f): e.Program(f+'.cpp'),\
  Split("""
    mapsoft_measure
    mapsoft_mark
    mapsoft_trackprofile
    mapsoft_srtmprofile
    """))
