Import ('env')
le = env.Copy()
mapsoft_libs = Split ("geo_io loaders utils jeeps")
graph_libs = Split("jpeg tiff png")

le.Program('test_fig', 'test_fig.cpp', LIBS=mapsoft_libs)
le.Program('test_poly', 'test_poly.cpp', LIBS=mapsoft_libs)
le.Program('test_mp', 'test_mp.cpp', LIBS=mapsoft_libs)
le.Program('fig_conv_podm', 'fig_conv_podm.cpp', LIBS=mapsoft_libs)
le.Program('fig_norm', 'fig_norm.cpp', LIBS=mapsoft_libs)
le.Program('fig_bbx_test', 'fig_bbx_test.cpp', LIBS=mapsoft_libs)
le.Program('test_geofig', 'test_geofig.cpp', LIBS = mapsoft_libs + graph_libs)
le.Program('mp2fig', 'mp2fig.cpp', LIBS = mapsoft_libs + graph_libs)

