Import ('env')

env.Library('utils', \
  Split("""
    options.cpp
    m_time.cpp m_color.cpp
    log.cpp
    iconv_utils.cpp spirit_utils.cpp
    image_gd.cpp
    pnm_shifter.cpp
  """))

env.Program(['options_test.cpp', 'options.cpp'])
env.Program(['options_read.cpp', 'options.cpp'])
