# coding: utf-8
Import ('env')
import os

env1 = env.Clone()

#### Method for pic 2 png mystery conversion
def pic2png(env, task):
   """Setup command for pic2png conversion by <name>:<cnt> argument"""
   name, sep, cnt = task.partition(':')
   env.Command(name+'.png', name+'.fig', "./make_pics %s.fig %s.png %s" % (name, name, cnt), chdir = 1)
env1.AddMethod(pic2png, 'Pic2Png')
####

map (lambda(s): env1.Pic2Png(s), Split("""
  avt kladb cross cerkov pam ohotn:88 bash:77 shaht:57 razv dom trig trig_hr kan
  ldp per per1a per1b per2a per2b per3a per3b pernk kladb pupyr yama skala
  bol_l:63 bol_h:62 redk vyr_n vyr_o ledn zd ur_vod por vdp
"""))

# vim: ft=python tw=0
