Import ('env_cairo')
e = env_cairo.Clone()

e.MDeps(Split("""
              vmap_renderer
              vmap mp fig geo_io geo loaders utils options 2d
              proj png jpeg tiff yaml
              """))

e.MLib('vmap_renderer',
       srcs = Split ("""
                     vmap_rend_cnt.cpp
                     vmap_rend_txt.cpp
                     vmap_rend_pic.cpp
                     vmap_renderer.cpp
                     """))

e.MProg("vmap_copy.cpp")
e.MProg("vmap_render.cpp")
e.MProg("vmap_mmb_filter.cpp")

