Import ('env')
e = env.Clone()

e.UseLibs('vmap')

e.Prepend(LIBS=["vmap_renderer"])
e.Library('vmap_renderer',\
  Split ("""
    vmap_rend_cnt.cpp
    vmap_rend_txt.cpp
    vmap_rend_pic.cpp
    vmap_renderer.cpp
  """))

e.Program("vmap_copy.cpp")
e.Program("vmap_render.cpp")
e.Program("vmap_fig_render.cpp")
e.Program("vmap_mmb_filter.cpp")
e.Program("vmap_fix_diff.cpp")

env.Install(env.bindir, Split("""
  vmap_copy vmap_render
"""))
