env = Environment ()

env.Library('vmap', \
    Split ("""
     vmap.cpp
     vmap_file.cpp
     vmap_fig.cpp
     vmap_mp.cpp
     vmap_vmap.cpp
     vmap_cnv.cpp
     vmap_filt.cpp
     vmap_labels.cpp
    """))

subdirs = Split ("""
                core/lib2d
                core/loaders
                core/utils
                core/options
                core/libgeo_io
                core/libgeo
                core/libmp
                core/libfig
                """)

env.Append (CCFLAGS=['-O2'])
env.Append (CPPPATH = ["../../core", "../libzn"])
env.Append (LIBPATH = map(lambda(s): "../../"+s, subdirs) )
env.Append (LIBPATH = ["../libzn", "."] )
env.Append (LIBS = Split("vmap zn mp fig geo_io geo loaders utils options 2d proj png jpeg tiff yaml") )

env.ParseConfig('pkg-config --cflags --libs cairomm-1.0,freetype2')

env.Program("vmap_copy.cpp")
env.Program("vmap_render.cpp")
