env = Environment ()

mapsoft_libs=Split("vmap mp fig geo_io geo loaders utils options 2d")
other_libs=Split("proj png jpeg tiff yaml")

env.Append (CCFLAGS=['-O2'])
env.Append (CPPPATH = ["../../core"])
env.Append (LIBPATH = map(lambda(s): "../../core/"+s, mapsoft_libs) )
env.Append (LIBS = [mapsoft_libs, other_libs] )

env.ParseConfig('pkg-config --cflags --libs cairomm-1.0,freetype2')

env.Program("vmap_copy.cpp")
env.Program("vmap_render.cpp")
env.Program("vmap_mmb_filter.cpp")

