all: make_map_gk get_legend get_print fig2pnm make_nom np2pt tx2pt

LDFLAGS= -L../libzn -L../libgeo_io -L../libgeo -L../jeeps \
         -L../loaders -L../libfig -L../libmp -L../utils -L../lib2d
LDLIBS= -lzn -lgeo_io -lgeo -ljeeps -lloaders\
        -lpng -ljpeg -ltiff -lusb -lyaml -lcurl\
        -lfig -lmp -lutils -l2d -lgd


CPPFLAGS=-I../ -g

make_map_gk:
make_nom:
make_nom2:

fig2pnm:     ../utils/pnm_shifter.cpp
pnm_cnt:     ../utils/pnm_shifter.cpp

get_print:
np2pt:
tx2pt:

get_legend:
get_text:
