#!/bin/bash

. ../settings.sh

MAP="all.fig"

if [ -z "$MAP" ]; then 
  echo "usage: $0"
  exit 1
fi

maps="$(mapsoft_vmap show_maps "$CONF" "$MAP" | cut -f1)"

for m in $maps; do
  echo "$m"
  mapsoft_vmap remove "$CONF"        "$m".fig all
  mapsoft_vmap copy   "$CONF" "$MAP" "$m".fig map "$m"
  mapsoft_vmap labels "$CONF"        "$m".fig
  mapsoft_vmap pics   "$CONF"        "$m".fig
done
