#!/bin/bash

VMAP="/home/sla/MS3/libzn-utils/mapsoft_vmap"
TX2PT="/home/sla/MS3/znaki2/tx2pt"

MAP="$1"
EDITOR="slazav"
CONF="./conf"

MAP=${MAP%%.*} # cutting all extentions

if [ -z "$MAP" -o -z "$CONF" -o -z "$EDITOR" ]; then 
  echo "usage: $0 <MAP>"
  exit 1
fi

$TX2PT "$CONF" "$MAP".fig "$MAP".fig

$VMAP update_fig  "$CONF" "$MAP" "$EDITOR" "$MAP".fig
$VMAP remove "$CONF" "$MAP".mp all
$VMAP copy   "$CONF" "$MAP".fig "$MAP".mp all
