#!/bin/sh -efu

. mapsoft_wp.sh
. mapsoft_map.sh

# map_wp_upd_gk -- update passes in rectangular maps.
# example: map_wp_upd_gk elbr.fig pamir.vmap
# Passes data are put into ./wpasses/ dir.

# Requires map.txt file with map description (see mapsoft_map.sh).
# At the moment I do not use this script.

mkdir -p -- wpasses
for i in "$@"; do
  base=$(basename ${i%.*})
  echo $i
  geom="$(map_data geom "$base")"

  cp -f -- "$i" "$i.bak"

  download_gk_wp "$geom" "wpasses/$base"

  mapsoft_vmap -v \
    wpasses/${base}_wp.mp --set_source westra_passes\
       --range_datum pulkovo --range_proj tmerc\
       --range "$geom" --range_action="select"\
    "$i" --split_labels --skip_source westra_passes\
    -o "$i"
done
