#!/bin/sh -efu

. mapsoft_wm.sh
. mapsoft_map.sh

# map_wp_upd_gk -- get wikimapia data for nom map
# example: map_wm_nom h45-110 ...

for i in "$@"; do
  echo $i
  download_ll_wm "$(nom2ll "$i")" "$i"
done
