#!/bin/sh -efu

name=$1

. map_functions.sh

style="$(get_map_par "$name" "style" "mmb")"
geom="$(get_map_par "$name" "geom" "")"

download_wp "$geom"

# crop passes to correct tmerc borders
mapsoft_vmap range_select tmerc pulkovo "$geom" "${name}_wp.mp"
