#!/bin/sh -efu

name=$1

. map_functions.sh

style="$(get_map_par "$name" "style" "mmb")"

[ -f "${name}_wp.mp" ] || map_pass_download "$name"

mapsoft_vmap remove "$name.fig" westra_passes
mapsoft_vmap copy   "${name}_wp.mp" "$name.fig"
mapsoft_vmap update "$name.fig"
