#!/bin/sh -efu

[ "$#" = 1 ] || {
  echo "usage: $0 <map name>"
  exit 1
}

name="$1"

. map_functions.sh

geom="$(get_map_par "$name" "geom" "")"
comm="$(get_map_par "$name" "comm" "")"
style="$(get_map_par "$name" "style" "default")"
rscale="$(get_map_par "$name" "rscale" "")"

[ -n "$geom" ] || {
  echo "unknown geometry for map $name"
  exit 1
}

[ -n "$rscale" ] || {
  echo "unknown rscale for map $name, set to 100000"
  rscale="100000"
}

./vmap_copy \
  -o "$name.fig"\
  --name "$comm" --rscale "$rscale" --style "$style"\
  --range "$geom" --range_datum "pulkovo" --range_proj "tmerc"\
  --set_brd_from_range
