#!/bin/sh -efu

. mapsoft_wp1.sh
. mapsoft_map.sh

# map_wp_upd_gk -- update passes in rectangular maps
# example: map_wp_upd_gk elbr.fig pamir.vmap

# Geometry information is read from maps.txt file:
# <base name> <geometry> <title>
# passes data is put into ./wpasses/ dir

mkdir -p -- wpasses
for i in "$@"; do
  base=$(basename ${i%.*})
  echo $i
  geom="$(map_data geom "$base")"

  cp -f -- "$i" "$i.bak"

  download_gk_wp "$geom" "wpasses/$base"

  mapsoft_vmap -v \
    wpasses/${base}_wp.mp --set_source westra_passes\
       --range_datum pulkovo --range_proj tmerc\
       --range "$geom" --range_action="select"\
    "$i" --split_labels --skip_source westra_passes\
    -o "$i"
done
