#!/bin/sh -efu

name=$1

. map_functions.sh

geom="$(get_map_par "$name" "geom" "")"

download_gl "$geom"

# crop passes to correct tmerc borders
mapsoft_vmap range_select tmerc pulkovo "$geom" "${name}_gl.mp"
