#!/bin/sh -efux

. mapsoft_gl.sh
. mapsoft_map.sh

# map_gl_gk_update -- update glaciers in rectangular maps.
# example: map_gl_gk_update elbr.fig pamir.vmap
# Data are put into ./glims/ dir.

# Requires map.txt file with map description (see mapsoft_map.sh).
# At the moment I do not use this script.

mkdir -p -- glims
for i in "$@"; do
  base=$(basename ${i%.*})
  echo $i
  geom="$(map_data geom "$base")"

  cp -f -- "$i" "$i.bak"

  download_gk_gl "$geom" "glims/$base"

  mapsoft_vmap -v \
    glims/${base}_gl.mp --set_source glims\
       --range_datum pulkovo --range_proj tmerc\
       --range "$geom" --range_action="select"\
    "$i" --split_labels --skip_source glims\
    -o "$i"
done
