#!/bin/sh -efu

# Make empty Soviet nomenclature map

[ "$#" = 3 ] || {
  echo "usage: $0 <map name> <style> <rscale>"
  echo "  map_name: j43-061.vmap, j44-001-1.fig ..."
  echo "  style: hr, mmb"
  echo "  rscale: 50000, 100000 ..."
  exit 1
}


name="$1"
style="$2"
rscale="$3"

base=$(basename ${name%.*})

mapsoft_vmap \
  -o "$name"\
  --name "$base" --rscale "$rscale" --style "$style"\
  --range_nom "$base" --set_brd_from_range
