Import('env')
e=env.Clone()
e.UseLibs('utils srtm')

e.Library('layers', \
    Split ("""
        layer.cpp
        layer_geomap.cpp
        layer_trk.cpp
        layer_wpt.cpp
        layer_srtm.cpp
        layer_pano.cpp
     """))
