Import ('env')
e=env.Clone()
e.UseLibs('libxml-2.0 libzip')

e.Library('geo_io', \
    Split ("""
    filters.cpp
    io.cpp
    io_gps.cpp
    io_gu.cpp
    io_kml.cpp
    io_gpx.cpp
    io_oe.cpp
    io_js.cpp
    io_xml.cpp
    io_zip.cpp
    geofig.cpp
     """))
e=env.Clone()
e.UseLibs('geo_io')
e.Program("catgeo.cpp")
