Import ('env')
e=env.Clone()

e.MLib('geo_io',
       srcs = Split ("""
                     filters.cpp
                     io.cpp
                     io_gps.cpp
                     io_gu.cpp
                     io_kml.cpp
                     io_oe.cpp
                     io_xml.cpp
                     o_img.cpp
                     o_tiles.cpp
                     geofig.cpp
                     """),
       deps = ['cairo'])
