Import ('env')

env.MLib('geo',
         srcs = Split ("""
                       geo_convs.cpp
                       geo_data.cpp
                       geo_types.cpp
                       geo_refs.cpp
                       geo_nom.cpp
                       """))
