Import ('env')
le = env.Clone()
le.Library('geo_io', \
    Split ("""
    filters.cpp
    io.cpp
    io_gps.cpp
    io_gu.cpp
    io_kml.cpp
    io_oe.cpp
    io_xml.cpp
    o_img.cpp
    geofig.cpp
     """))
