Import('env')
e=env.Clone()
e.ParseConfig('pkg-config --cflags --libs vmap')
e.Prepend(LIBS=["vmap2"])

e.Library('vmap2', \
    Split ("""
        legend.cpp
        vmap.cpp
        vmap_io.cpp
        vmap_id.cpp
        vmap_fig.cpp
     """))

e.Program("vmap_putfig.cpp")
e.Program("vmap_getfig.cpp")


