
mapsoft_libs=Split("vmap2 vmap fig mp geo_io geo loaders jeeps options utils 2d yaml tiff png jpeg proj")
other_libs=Split("yaml proj png jpeg tiff")

Import('env')
e=env.Clone()
e.Prepend(LIBS=[mapsoft_libs, other_libs])

e.Library('vmap2', \
    Split ("""
        legend.cpp
        vmap.cpp
        vmap_io.cpp
        vmap_id.cpp
        vmap_fig.cpp
     """))

e.Program("vmap_putfig.cpp")
e.Program("vmap_getfig.cpp")


