.TH "mapsoft_convert" "1" "" "slazav@altlinux.org" "mapsoft"
.SH "NAME"
.LP 
Convert geodata to various formats
.SH "SYNTAX"
.LP 
mapsoft_convert <options> <input files> \-o <output file>
.SH "MAIN OPTIONS"
.TP 
\fB\-\-help, \-h\fR
Show help message
.TP 
\fB\-\-out=<file>, \-o <file>\fR
Specify output file (required)
.TP 
\fB\-\-skip=<string>, \-s <string>\fR
Skip some types of data (see below)
.TP 
\fB\-\-rescale_maps <factor>\fR
Rescale map references
.TP 
\fB\-\-shift_maps <x>,<y>\fR
Shift map references
.SH "INPUT FILES"
.TP 
mapsoft XML\-like format
.TP 
old garmin\-utils format (tracks and waypoints)
.TP 
OziExplorer format (tracks, waypoints and map references)
.TP 
geofig format
.TP 
Garmin GPS device via libusb or serial port (use "usb:" or serial device name as a input file name)
.SH "SKIPPING DATA"
.LP 
You may use \fB\-s <string>\fR or \fB\-\-skip=<string>\fR option to skip some data
If string contains letter: 
.TP 
"m" \-\- skip maps 
.TP 
"w" \-\- skip waypoints 
.TP 
"t" \-\- skip tracks 
.TP 
"a" \-\- skip ACTIVE LOG track 
.TP 
"o" \-\- skip all tracks excluding ACTIVE LOG
.SH "OUTPUT FILE"
.LP 
You must provide name for output file (\-o or \-\-out option).
File format is determined by its extension:
.TP 
\fB.xml\fR
mapsoft XML\-like format (all data will be written to one file)
.TP 
\fB.gu\fR
old garmin\-utils format (tracks and waypoints only)
.TP 
\fB.wpt,.plt,.map,.oe\fR
OziExplorer format. (Each track, waypoint set or map reference will be written in a separate .plt, .wpt or .map file)
.TP 
\fB.zip\fR
zipped OziExplorer files
.TP 
\fB.kml\fR
Google KML format (tracks and waypoint only, lat,lon,alt,name data only)
.TP 
\fB.kmz\fR
zipped kml
.TP 
\fB.tif,.tiff,.jpg,.jpeg\fR
raster image (see below for additional options)
.TP 
\fB.fi g\fR
unstable now
.TP 
\fB.htm,.html\fR
unstable now
.LP 
If output file is "usb:" data will be sent to Garmin GPS
device via libusb. If output file is a character device
data will be sent to Garmin GPS via serial port.
.SH "OPTIONS FOR RASTER IMAGE OUTPUT"
.TP 
\fB\-d <name>,\-\-datum=<name>\fR
datum (pulkovo, wgs84, ...)
.TP 
\fB\-p <name>,\-\-proj=<name><fr>
projection (lonlat, tmerc, ...)
.TP 
\fB\-g <AxB+C+D>,\-\-geom=<AxB+C+D>\fR
geometry (in projection units)

.LP 
Default datum is pulkovo, default projection is tmerc..
Default geiometry is calculated from geodata (not map) range.

.TP  
\fB\-\-fig=<file>\fR
write referenced geofig file for image
.TP 
\fB\-\-map=<file>\fR
write OziExplorer map file for image
.TP 
\fB\-\-htm=<file>\fR
write HTML map.
.TP 
\fB\-\-scale <v>\fR
map scale (1e\-5 means 1km per 1cm).
.TP 
\fB\-\-rscale <v>\fR
reversed map scale, 1/scale
.TP 
\fB\-\-dpi <v>\fR
dots per inch
.TP 
\fB\-\-factor <v>\fR
rescale factor (default: 1)

.LP 
By default the scale of resulting map is the same as one of the first.
input map. If there is no maps on input scale=1e\-5,dpi=200.
You may change default value using factor parameter or
rewrite it by dpi and scale (or rscale) parameters
Note: using rscale=100000, dpi=300 and rscale=50000, dpi=150
gave same images but different geofig files.
Note: rscale value overwrites scale.

.TP 
\fB\-\-data_marg=<m>\fR
When detecting geometry of geodata ddd margings around it (in meters).

.TP 
\fB\-\-draw_borders=(1|0)\fR
draw input map borders
.TP 
\fB\-\-jpeg_quality=<n>\fR
jpeg quality
.TP 
\fB\-\-max_image=<W,H>\fR
maximum image size (default: 5000,5000)

.TP 
\fB\-\-google=<scale>\fR
add google image of specified scale
.TP 
\fB\-\-ks=<scale>\fR
add ks image of specified scale
.TP 
\fB\-\-google_dir=<dir>\fR
directory for google images
.TP 
\fB\-\-ks_dir=<dir>\fR
directory for ks images
.TP 
\fB\-\-download=(1|0)\fR
turn on downloading of ks and google images
.SH "EXAMPLES"
.TP 
\fBmapsoft_convert /maps/*.map \-o maps.xml\fR
Convert Ozi map files to a single xml
.TP 
\fBmapsoft_convert /dev/ttyUSB0 \-s o \-o data.plt\fR
Download waypoints and active log from GPS device and write them
down in Ozi format files data.plt and data.wpt
.TP 
\fBmapsoft_convert data.plt data.wpt \-o data.kmz\fR
Convert waypoints and track to packed kml format
.TP 
\fBmapsoft_convert maps.xml data.plt \-o mymap.jpg \-\-map=mymap.map\fR
Create jpeg image with map from maps.xml and data from data.plt. Create also a map\-file for this image
.TP 
\fBmapsoft_convert \-\-ks=14 \-\-ks_dir=~/KS \-\-download=1 data.plt \-o mymap.jpg\fR
Create jpeg image with KS image and your dataand map\-file for it. ./KS directory must exist.
.SH "AUTHORS"
.LP 
Vladislav Zavjalov <slazav@altlinux.org>,
Max Ushakov,
Tim Alexeevsky
.SH "SEE ALSO"
.LP 
.TP 
mapsoft (not written yet)
.TP 
mapsoft_vmap (not written yet)
.TP 
mapsoft_mapview (not written yet)
