Import('env')

def DefineProg(name):
    env.MProg(name,
              srcs = [name + '.cpp'],
	      deps = Split("""
                       geo_io
                       geo
                       loaders
                       jeeps
                       fig
                       mp
                       utils
                       options
                       2d
                       """))

map (lambda(f): DefineProg(f),
  Split("""
    mapsoft_add2fig
    mapsoft_convert
    mapsoft_pt2map
    mapsoft_mapcnv
    mapsoft_mapcnv1
    mapsoft_getks
    mapsoft_getks_ll
    mapsoft_getks_nom
    mapsoft_getgoogle
    mapsoft_mkmap
    mapsoft_ref
    mapsoft_toxyz
    mapsoft_map2fig
    mapsoft_srtm2fig
    mapsoft_fig2fig
    mapsoft_calc_nom2ll
    mapsoft_pano

    convs_pt2pt
    convs_map2pt
    convs_nom
    """))

env.Install(env.man1dir, Split("""
  mapsoft_convert.1
"""))

env.Install(env.bindir, Split("""
  mapsoft_convert mapsoft_add2fig
  convs_pt2pt convs_map2pt convs_nom
"""))

