Import ('env')
e = env.Clone()

e.UseLibs('vmap')

e.Program('mapsoft_vmap.cpp')
e.Program('fig2pnm.cpp')
e.Program('get_print.cpp')
e.Program('get_print_mmb.cpp')
e.Program('make_map_gk.cpp')
e.Program('make_nom.cpp')

